spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
    time-zone: GMT+8
  mvc:
    async:
      request-timeout: 5s
  servlet:
    multipart:
      enabled: false
  data:
    web:
      pageable:
        page-parameter: page # 当前页参数名 默认为 page
        size-parameter: size # 当前页参数名 默认为 size
        default-page-size: 20 # 分页大小 默认为 20
      sort:
        sort-parameter: orderBy # 字段排序参数名 默认为 sort, mysql排序为orderBy
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: BlogHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
      database: mysql
      hibernate:
        ddl-auto: update
#      database-platform: org.hibernate.dialect.MySQL5Dialect
      database-platform: org.hibernate.dialect.MySQLMyISAMDialect
      open-in-view: true
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username:
    password:
    port: 25
    protocol: smtp
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 127.0.0.1 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
#    lettuce:
#      pool:
#        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
#        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-idle: 8 # 连接池中的最大空闲连接
#        min-idle: 0 # 连接池中的最小空闲连接
#    timeout: 0 # 连接超时时间（毫秒）

#  quartz:
#    job-store-type: memory

server:
  port: 9999
  servlet:
    context-path: /
  connection-timeout: 10s
  compression:
    enabled: true
    mime-types: application/json, text/html, text/xml, text/plain, text/css, text/javascript, application/javascript
    min-response-size: 1024
#  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    # 不要设置过大，如果过大，启动项目会报错：打开文件数过多
#    io-threads: 2
    # 阻塞任务线程池, 当执行类似servlet请求阻塞IO操作, undertow会从这个线程池中取得线程
    # 它的值设置取决于系统线程执行任务的阻塞系数，默认值是IO线程数*8
#    worker-threads: 16
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分，不要设置太大，以免影响其他应用，合适即可
#    buffer-size: 1024
    # 是否分配的直接内存(NIO直接分配的堆外内存)
#    direct-buffers: true
    # 每个区分配的buffer数量 , 所以pool的大小是buffer-size * buffers-per-region
    # buffers-per-region: 1024 已过时.


