spring:
  thymeleaf:
    cache: true
  jpa:
    show-sql: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/msjuseSSL=false&amp;useUnicode=true&amp;characterEncoding=utf8mb4
    username: root
    password:
    hikari:
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
  resources:
    chain:
      # 启用缓存
      cache: true
      # 开启gzip压缩
      gzipped: true
    cache:
      cachecontrol:
        max-age: 3600s
      # 资源缓存时间，单位秒
      period: 2592000s #单位:秒, 此处为30天
wechat:
  app-id: d
  app-secret: e
  token: f

logging:
  path: ./logs/



